#!/bin/bash

FILENAME=$(date +"%Y%m%d_%H%M")
LOC='/home/pi/workspace/AIBot'

#record with sudo since arecord seems to want root privledges
arecord -D "plughw:1,0" -f dat -d 10 ${LOC}/${FILENAME}.wav
[ $? -eq 0 ] || exit $?

#convert to mp3 (64Kpbs) 
lame -b 64 ${LOC}/${FILENAME}.wav ${LOC}/${FILENAME}.mp3
[ $? -eq 0 ] || exit $?


NOTIFY_EMAIL=tarek.taha@gmail.com
MODTIME=$(stat -c %y ${LOC}/${FILENAME}.mp3)
DATE=$(date --date="${MODTIME}" +%Y-%m-%d)

#send email
echo "Done!" | mail -s "Podcast ${DATE} - Upload Complete" $NOTIFY_EMAIL
