#!/bin/bash

count=1
lastsize=0
rec=0
first=1

# Der Soundchip des RPI erzeugt vor und nach der Wiedergabe ein Knacken. Deutlich bessere Ergebnisse liefert eine USB-Soundkarte, wie man sie bereits für rund fünf Euro bekommt. Damit mplayer die USB-Soundkarte benutzt, ändert man den Parameter "-ao alsa:device=hw=0.0" in "-ao alsa:device=hw=1.0".

function sayAll {
INPUT=$*
ary=($INPUT)
for key in "${!ary[@]}"
do
SHORTTMP[$STRINGNUM]="${SHORTTMP[$STRINGNUM]} ${ary[$key]}"
LENGTH=$(echo ${#SHORTTMP[$STRINGNUM]})

if [[ "$LENGTH" -lt "100" ]]; then

SHORT[$STRINGNUM]=${SHORTTMP[$STRINGNUM]}
else
STRINGNUM=$(($STRINGNUM+1))
SHORTTMP[$STRINGNUM]="${ary[$key]}"
SHORT[$STRINGNUM]="${ary[$key]}"
fi
done
for key in "${!SHORT[@]}"
do
say() { mplayer -ao alsa:device=hw=0.0 -really-quiet -http-header-fields "User-Agent:Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22m" "http://translate.google.com/translate_tts?tl=en&q=${SHORT[$key]}";}
say $*
done
}

#sox -t alsa hw:1,0 test.wav silence 1 0 2% -1 0.5 5% &
sox -r 16000 -t alsa hw:2,0 recording.flac silence  1 0 2% -1 0.5 5% &
#sox -r 16000 -t alsa hw:2,0 default recording.flac silence  1 0.1 3% 1 0.5 5% &
#rec --encoding signed-integer --bits 16 --channels 1 --rate 16000 test.wav silence 1 0 2% -1 0.5 5%

sox_pid=$!

while [ $count -le 9 ]
do
   
size=$(stat --printf="%s" recording.flac)
echo $size
if [ $size -gt $lastsize ]
	then
		if [ $first -eq 0 ]
		then
			echo "Recording!"
			rec=1
		else
			first=0
		fi
	else
		if [ $rec -eq 1 ]
			then
				echo "Submitting"
				kill $sox_pid
				#ffmpeg -loglevel panic -y -i test.wav -ar 16000 -acodec flac file.flac
				#wget -q -U "Mozilla/5.0" --post-file file.flac --header "Content-Type: audio/x-flac; rate=16000" -O - "http://www.google.com/speech-api/v1/recognize?lang=en&client=chromium" | cut -d\" -f12 >stt.txt
				wget -q -U "Mozilla/5.0" --post-file recording.flac --header="Content-Type: audio/x-flac; rate=16000" -O - "https://www.google.com/speech-api/v2/recognize?xjerr=1&client=chromium&lang=en-US&maxresults=10&pfilter=0&xjerr=1&key=AIzaSyByL8siBe1B6NSBPkVwCLr10_xkRJHVxdg" | cut -d\" -f12 >stt.txt
				COMMAND=$(cat stt.txt)
				echo $COMMAND
				# sayAll "$(cat stt.txt)"
				if [[ $COMMAND =~ "Command" ]]
				then
					echo "Recognized voice command!"
 					sayAll "Recognized voice command! I could execute any shell command now!"
				elif [[ $COMMAND =~ "Weather" ]]
				then
					echo "Checking weather!"
					ANSWER=$(python askWolfram.py $COMMAND)
 					#say "I would ask you now to read the weather forecast! Bring it to me!"
 					sayAll $ANSWER
				elif [[ $COMMAND != "" ]]
				then
 					echo "Asking Wolfram"
 					ANSWER=$(python askWolfram.py $COMMAND)
 					echo $ANSWER
					sayAll $ANSWER
				else
          echo "Don't know what you just said"
        fi

			sleep 1
			bash soxSay
		else
			echo "Listening to your questions ..."
		fi
		rec=0
fi

lastsize=$size

sleep 1

done

